import type { ExegesisPlugin, ExegesisPluginContext } from "exegesis-express";
import process from "node:process";
const NODE_ENV = process.env.NODE_ENV || "development";

export default function setServerHostname(): ExegesisPlugin {
  return {
    info: {
      name: "set-server-suffix",
    },
    makeExegesisPlugin: () => {
      return {
        postRouting: (ctx: ExegesisPluginContext) => {
          const url = new URL(`http://${ctx.req.headers.host}`);
          if (NODE_ENV === "production") url.protocol = "https";
          ctx.api.serverObject = {
            url: url.toString(),
            description: `${NODE_ENV} server. Autogenerated depending on host`,
          };
          ctx["ectx"]["server"] = url.toString();
        },
      };
    },
  };
}
